name: flutter_ravepay
description: Flutter integration for Flutterwave's Rave payment platform.
version: 0.2.1
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/flutter_ravepay

flutter:
  plugin:
    androidPackage: io.github.jogboms.flutterravepay
    pluginClass: FlutterRavepayPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"
  flutter: ">=0.5.1 <2.0.0"
